//RESTAURANTS
### 
GET http://localhost:8080/api/comments


### 
GET http://localhost:8080/api/comment?id=64365594ecd15ae29bc3c030


###
GET http://localhost:8080/api/comments/latestcomments


//create
### 
POST http://localhost:8080/api/comment
Content-Type:  application/json

# {
#     "restaurantId": "642d5427e36e9ce7441dc528",
#     "comment": "good",
#     "rate": 5
#   }

  {
    "restaurantId": "6436640d4da9fe33c872a065",
    "userId": "643663704fa5df76a9ed8f64",
    "comment": "not bad",
    "rate": 3
  }

###
DELETE http://localhost:8080/api/comment?id=643664f2e7948e58e1177365

###
PUT  http://localhost:8080/api/comment?id=6438052a6e01f136e49bcc98
Content-Type: application/json

{ 
  "restaurantId": "6436640d4da9fe33c872a065",
    "userId": "643663704fa5df76a9ed8f64",
    "comment": "not ",
    "rate": 3
}
