
### 
GET http://localhost:9000/api/comments


### 
GET http://localhost:9000/api/comment?id=643e76567bbb3606eb8f1e91




# ??? GET LATEST COMMENTS
###
GET http://localhost:9000/api/latestcomments



### ??? GET TOP FOODS

###
GET http://localhost:9000/api/gettopfoods


//create
### 
POST http://localhost:9000/api/comment
Content-Type:  application/json

  {
    "restaurantId": "643e77267bbb3606eb8f1eac",
    "foodId": "643e74d312b52208eb916aad",
    "userId": "643e6eea34d6ab3068e43935",
    "comment": "food test",
    "rate": 1
  }

###
DELETE http://localhost:9000/api/comment?id=643e76567bbb3606eb8f1e91

###
PUT  http://localhost:9000/api/comment?id=643e76567bbb3606eb8f1e91
Content-Type: application/json

{ 
    "restaurantId": "643e6eff34d6ab3068e43938",
    "foodId": "643e74d312b52208eb916aad",
    "userId": "643e6eea34d6ab3068e43935",
    "comment": "Excellent food",
    "rate": 5
}
