//RESTAURANTS
### 
GET http://localhost:8080/api/menus


### 
GET http://localhost:8080/api/menu?id=64181528254fc0ac96d2f320


//create
### 
POST http://localhost:8080/api/menu
Content-Type:  application/json

{
    "name": "Erdenedari ",
    "userName": "Daria",
    "email": "ch.erdenedari0601@gmail.com"
    "phone": 99238974,
    "password": "86238974",
    "point": [1200],
    "userType": "Admin",
    "img": ["linkHere"],
  },

###
DELETE http://localhost:8080/api/menu?id=64181528254fc0ac96d2f320

###
PUT  http://localhost:8080/api/menu?_id=6418155a254fc0ac96d2f324
Content-Type: application/json

{ 
}
