//RESTAURANTS
### 
GET http://localhost:9000/api/restaurants



//TOP RESTAURANTs
###
GET http://localhost:9000/api/toprestaurants


### 
GET http://localhost:9000/api/restaurant?id=64380408224ea68e2e09e18c


//create
### 
POST http://localhost:9000/api/restaurant
Content-Type:  application/json

{
    "restaurantName": "Arig Anya Shangrila",
    "address": 
      {
        "district": "Хан-уул дүүрэг",
        "street": "П.Гэндэнгийн гудамж",
        "building": "Shangri-La",
        "address": "Shangri-La молл 3 давхарт",
        "location": {
          "type": "Point",
          "coordinates": [47.9163252, 106.9188089]
        }
      },
       "restaurantRate": [
    ],
    "cuisineType": ["Mongolia"],
    "contact": {
      "phone": 70007020,
      "facebook": "https://www.facebook.com/ArigAnya",
      "Instagram": "none",
      "link": "none"
    },
    "email":"Office@ariganya.com",
    "img": ["linkHere"],
    "logoImg": "url here",
    "schedule": {
      "weekday": { "open": 10, "close": 22 },
      "weekend": { "open": 10, "close": 20 }
    }
  }


###
DELETE http://localhost:9000/api/restaurant?id=6436640d4da9fe33c872a065

###
PUT  http://localhost:9000/api/restaurant?id=643803fa224ea68e2e09e186
Content-Type: application/json

{ 
   "restaurantName": "dsakk Shangri-La",
    "address": 
      {
        "district": "Сүхбаатар дүүрэг",
        "street": "П.Гэндэнгийн гудамж",
        "building": "Shangri-La",
        "address": "Shangri-La молл 3 давхарт",
        "location": {
          "type": "Point",
          "coordinates": [47.9163252, 106.9188089]
        }
      },
    "restaurantRate": [
      {
        "rateType": "foodRate",
        "userId": "642d4cb3f18becf2efdc6a18",
        "score": 5,
        "comment": "anhnii comment shuu hool goy"
      },
      {
         "rateType": "foodRate",
        "userId": "642d4cb3f18becf2efdc6a18",
        "score": 2,
        "comment": "anhnii comment shuu hool goy"
      }
    ],
    "cuisineType": ["Korea"], 
    "contact": {
      "phone": 70007020,
      "facebook": "",
      "Instagram": "none",
      "link": "none"
    },
    "img": ["linkHere"],
    "logoImg": "url here",
    "schedule": {
      "weekday": { "open": 10, "close": 22 },
      "weekend": { "open": 10, "close": 20 }
    }
}



###
POST http://localhost:9000/api/restaurant/search
Content-Type: application/json

{
  "searchTxt": "arig"
}



### 
POST http://localhost:9000/api/search
Content-Type: application/json

{
  "price" : "10000-15000", // null 
  "rate" : "", // null, 1ees , 2oos , 3oos, 4uus
  "location" : "" ,//buseer tuv, baruun , zuun (location range)
  "cuisineType" : ""// enum
}