//RESTAURANTS
### 
GET http://localhost:8080/api/restaurants


### 
GET http://localhost:8080/api/restaurant?id=642e54364dbdb601b37980a2


//create
### 
POST http://localhost:8080/api/restaurant
Content-Type:  application/json

{
    "restaurantName": "The Bull",
    "address": 
      {
        "district": "Сүхбаатар дүүрэг",
        "street": "П.Гэндэнгийн гудамж",
        "building": "Shangri-La",
        "address": "Shangri-La молл 3 давхарт",
        "location": {
          "type": "Point",
          "coordinates": [47.9163252, 106.9188089]
        }
      },
    "restaurantRate": [
      {
        "rateType": "foodRate",
        "userId": "642d4cb3f18becf2efdc6a18",
        "score": 5,
        "comment": "anhnii comment shuu hool goy"
      }
    ],
    "cuisineType": ["Mongolia"],
    "contact": {
      "phone": 70007020,
      "facebook": "https://www.facebook.com/ArigAnya",
      "Instagram": "none",
      "link": "none"
    },
    "email":"Office@ariganya.com",
    "img": ["linkHere"],
    "logoImg": "url here",
    "schedule": {
      "weekday": { "open": 10, "close": 22 },
      "weekend": { "open": 10, "close": 20 }
    }
  }


###
DELETE http://localhost:8080/api/restaurant?id=6433afa9a38a3efc7d7e841a

###
PUT  http://localhost:8080/api/restaurant?id=642e54364dbdb601b37980a1
Content-Type: application/json

{ 
   "restaurantName": "dsakk Shangri-La",
    "address": 
      {
        "district": "Сүхбаатар дүүрэг",
        "street": "П.Гэндэнгийн гудамж",
        "building": "Shangri-La",
        "address": "Shangri-La молл 3 давхарт",
        "location": {
          "type": "Point",
          "coordinates": [47.9163252, 106.9188089]
        }
      },
    "restaurantRate": [
      {
        "rateType": "foodRate",
        "userId": "642d4cb3f18becf2efdc6a18",
        "score": 5,
        "comment": "anhnii comment shuu hool goy"
      }
    ],
    "cuisineType": ["Mongolia"], 
    "contact": {
      "phone": 70007020,
      "facebook": "",
      "Instagram": "none",
      "link": "none"
    },
    "img": ["linkHere"],
    "logoImg": "url here",
    "schedule": {
      "weekday": { "open": 10, "close": 22 },
      "weekend": { "open": 10, "close": 20 }
    }
}
